language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hasanmubarok/docker-react -f Dockerfile.dev .

scripts:
  - docker run hasanmubarok/docker-react npm run test --  -- coverage